export enum pairSymbolTickerTypes {
  FETCH_PAIR_SYMBOL_TICKER_REQUEST = 'FETCH_PAIR_SYMBOL_TICKER_REQUEST',
  FETCH_PAIR_SYMBOL_TICKER_SUCCESS = 'FETCH_PAIR_SYMBOL_TICKER_SUCCESS',
  FETCH_PAIR_SYMBOL_TICKER_FAILURE = 'FETCH_PAIR_SYMBOL_TICKER_FAILURE',
}
